# Generated by Django 3.1.7 on 2021-03-04 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='image',
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='user',
        ),
        migrations.AddField(
            model_name='sheet',
            name='chords',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_title', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sheets', models.ManyToManyField(to='sheets.Sheet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
