# Generated by Django 3.1.7 on 2021-03-04 06:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_auto_20210304_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='key',
            field=models.CharField(default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
    ]
