# Generated by Django 3.1.7 on 2021-03-04 09:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0003_sheet_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='chords',
        ),
        migrations.AddField(
            model_name='sheet',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
