# Generated by Django 3.1.7 on 2021-03-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0004_auto_20210304_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='file',
            field=models.TextField(),
        ),
    ]
