# Generated by Django 3.1.7 on 2021-03-04 12:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0006_auto_20210304_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='artist',
            field=models.CharField(default=datetime.datetime(2021, 3, 4, 12, 4, 28, 75022, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
