# Generated by Django 3.1.7 on 2021-03-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0007_sheet_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='sheets',
            field=models.ManyToManyField(blank=True, to='sheets.Sheet'),
        ),
    ]
