# Generated by Django 3.1.7 on 2021-03-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0009_auto_20210307_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='sheets',
            field=models.ManyToManyField(to='sheets.Sheet'),
        ),
    ]
